sudo: required
services:
    - docker

before_install:
    - docker build -t sanu0602/docker-reactapp -f Dockerfile.dev .

services:
    - docker run -e CI=true sanu0602/docker-reactapp npm run test -- --coverage